In [3]:
import numpy as np
a = np.array([[1], [2]])
b = np.array([[3], [4]])
r1 = np.kron(a, b)
r2 = np.outer(a, b)
r3 = np.kron(a, b.T)

In [4]:
print(r1)
print(r2)
print(r3)

[[3]
 [4]
 [6]
 [8]]
[[3 4]
 [6 8]]
[[3 4]
 [6 8]]


In [6]:
import numpy as np

x = np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])
print(x[:,0])
print(x[:,0])

[0 2 4 6 8]
[0 2 4 6 8]
